// constants/nigerian-locations.ts
export const NIGERIAN_STATES = [
  'Abia',
  'Adamawa',
  'Akwa Ibom',
  'Anambra',
  'Bauchi',
  'Bayelsa',
  'Benue',
  'Borno',
  'Cross River',
  'Delta',
  'Ebonyi',
  'Edo',
  'Ekiti',
  'Enugu',
  'FCT',
  'Gombe',
  'Imo',
  'Jigawa',
  'Kaduna',
  'Kano',
  'Katsina',
  'Kebbi',
  'Kogi',
  'Kwara',
  'Lagos',
  'Nasarawa',
  'Niger',
  'Ogun',
  'Ondo',
  'Osun',
  'Oyo',
  'Plateau',
  'Rivers',
  'Sokoto',
  'Taraba',
  'Yobe',
  'Zamfara',
]

export const NIGERIAN_CITIES = [
  'Lagos',
  'Abuja',
  'Port Harcourt',
  'Kano',
  'Ibadan',
  'Benin City',
  'Kaduna',
  'Enugu',
  'Abeokuta',
  'Warri',
  'Calabar',
  'Uyo',
  'Umuahia',
  'Owerri',
  'Akure',
  'Ado-Ekiti',
  'Osogbo',
  'Ilorin',
  'Jos',
  'Maiduguri',
  'Yola',
  'Bauchi',
  'Makurdi',
  'Minna',
  'Lokoja',
  'Asaba',
  'Awka',
  'Ogbomosho',
  'Onitsha',
  'Aba',
  'Ijebu-Ode',
  'Sokoto',
  'Gusau',
  'Katsina',
]

export const EXPERIENCE_LEVELS = [
  { value: '0', label: 'Less than 1 year' },
  { value: '1', label: '1 year' },
  { value: '2', label: '2 years' },
  { value: '3', label: '3 years' },
  { value: '5', label: '5+ years' },
  { value: '10', label: '10+ years' },
]

export const SPECIALTIES = [
  'Residential',
  'Commercial',
  'Luxury Homes',
  'Property Management',
  'Real Estate Investment',
  'Land Acquisition',
]
