import type { Metadata } from 'next'
import { AuthProvider } from '@/contexts/AuthContext'
import { LoadingProvider } from '@/contexts/LoadingContext'

import AgentLayout from '@/components/agents/AgentLayout'
import Chatbot from '@/components/chatbot/Chatbot'
import { ToastProvider } from '@/components/ToastProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <LoadingProvider>
      <AuthProvider>
        <AgentLayout>{children}</AgentLayout>

        <ToastProvider />
        <Chatbot />
      </AuthProvider>
    </LoadingProvider>
  )
}
